# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('del_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
